# Generated by Django 5.0.4 on 2024-05-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gallerycarousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryCarousel',
        ),
    ]
