# Generated by Django 5.0.4 on 2024-05-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallerypage_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryCarouselImages',
        ),
    ]
