# Generated by Django 5.0.4 on 2024-06-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_gallerycarouselimages'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandardPage',
            new_name='HomStandardPage',
        ),
    ]
