# Generated by Django 5.0.4 on 2024-06-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_homstandardpage_standardpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryPage',
            new_name='ArticlePage',
        ),
    ]
