# Generated by Django 5.0.4 on 2024-06-20 10:59

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_storiespage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiespage',
            name='body',
            field=wagtail.fields.StreamField([('stories', wagtail.blocks.StructBlock([('story_heading', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('story_description', wagtail.blocks.CharBlock(required=False)), ('story_item', wagtail.blocks.StreamBlock([('story_item', wagtail.blocks.StructBlock([('story_item_title', wagtail.blocks.CharBlock()), ('story_item_description', wagtail.blocks.RichTextBlock(required=False)), ('multi_embed_block', wagtail.blocks.StreamBlock([('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', icon='media', template='home/embed_block.html'))], required=False))]))], required=False))]))]),
        ),
    ]
