# Generated by Django 5.0.4 on 2024-07-08 09:14

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_storiespage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerypage",
            name="carousel",
            field=wagtail.fields.StreamField(
                [
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Insert an embed URL, this could be direct URL or share video URL",
                            icon="media",
                            template="home/embed_block.html",
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
