# Generated by Django 5.0.4 on 2024-09-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_newarticlepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlePage',
        ),
    ]
