# Generated by Django 5.2.2 on 2025-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='format',
            field=models.CharField(choices=[('LP', 'LP'), ('Singles', 'Singles'), ('7"', '7"'), ('10"', '10"'), ('12"', '12"')], default='LP', max_length=10),
        ),
    ]
