# Generated by Django 5.2.2 on 2025-08-24 13:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_record_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug (Optional)')),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('excerpt', models.TextField(help_text='Brief summary for the news listing page', max_length=300)),
                ('content', wagtail.fields.RichTextField()),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured news')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
