# Generated by Django 5.2.2 on 2025-08-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
