# Generated by Django 5.2.10 on 2026-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_newspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('constant_contact', 'Constant Contact'), ('none', 'None')], default='none', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Enable this integration')),
                ('mailchimp_api_key', models.CharField(blank=True, help_text='Mailchimp API Key', max_length=255)),
                ('mailchimp_list_id', models.CharField(blank=True, help_text='Mailchimp Audience/List ID', max_length=100)),
                ('mailchimp_server_prefix', models.CharField(blank=True, help_text="Mailchimp server prefix (e.g., 'us1', 'us2')", max_length=10)),
                ('sendgrid_api_key', models.CharField(blank=True, help_text='SendGrid API Key', max_length=255)),
                ('sendgrid_list_id', models.CharField(blank=True, help_text='SendGrid List ID', max_length=100)),
                ('constant_contact_api_key', models.CharField(blank=True, help_text='Constant Contact API Key', max_length=255)),
                ('constant_contact_access_token', models.CharField(blank=True, help_text='Constant Contact Access Token', max_length=255)),
                ('constant_contact_list_id', models.CharField(blank=True, help_text='Constant Contact List ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Integration',
                'verbose_name_plural': 'Newsletter Integrations',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='website', help_text='Source of subscription (e.g., website, admin)', max_length=50)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
